version: 1.0.0

kafkaCfg:
    common:
        properties:
            bootstrap.servers: adm:9092
    producer:
        messages_send: 1
        topic_name: lab
        data_file: data/flow.json  
        properties:
            client.id: vhl_producer
    stream:
        topic_name: lab
        properties:
            application.id: vhl-grp
            client.id: vhl_streams1
            group.id: vhl-grp
            commit.interval.ms: 3000
